# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'music_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13music_service.proto\"\x07\n\x05\x45mpty\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"1\n\x04Song\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\"G\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x05\x12\x10\n\x08song_ids\x18\x04 \x03(\x05\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x08UserList\x12\x14\n\x05users\x18\x01 \x03(\x0b\x32\x05.User\" \n\x08SongList\x12\x14\n\x05songs\x18\x01 \x03(\x0b\x32\x05.Song\",\n\x0cPlaylistList\x12\x1c\n\tplaylists\x18\x01 \x03(\x0b\x32\t.Playlist2{\n\x0cMusicService\x12\x1e\n\tListUsers\x12\x06.Empty\x1a\t.UserList\x12\x1e\n\tListSongs\x12\x06.Empty\x1a\t.SongList\x12+\n\x11ListUserPlaylists\x12\x07.UserId\x1a\r.PlaylistListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_USER']._serialized_start=32
  _globals['_USER']._serialized_end=79
  _globals['_SONG']._serialized_start=81
  _globals['_SONG']._serialized_end=130
  _globals['_PLAYLIST']._serialized_start=132
  _globals['_PLAYLIST']._serialized_end=203
  _globals['_USERID']._serialized_start=205
  _globals['_USERID']._serialized_end=225
  _globals['_USERLIST']._serialized_start=227
  _globals['_USERLIST']._serialized_end=259
  _globals['_SONGLIST']._serialized_start=261
  _globals['_SONGLIST']._serialized_end=293
  _globals['_PLAYLISTLIST']._serialized_start=295
  _globals['_PLAYLISTLIST']._serialized_end=339
  _globals['_MUSICSERVICE']._serialized_start=341
  _globals['_MUSICSERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
